# This is a values file that works with a local deployment
deployment:
  enabled: true
  name: azureinterview-broken-deployment
  replicas: 1
  securityContext:
    runAsNonRoot: true
    runAsUser: 1337
container:
  name: azureinterview-broken-container
  port: 8080
  imagePullPolicy: Always
livenessProbe:
  httpGet:
    path: /healthz
readinessProbe:
  httpGet:
    path: /healthz
resources:
  limits:
    cpu: "0.5"
    memory: "512Mi"
  requests:
    cpu: "0.1"
    memory: "128Mi"
image:
  repository: 
  tag: latest
env:
  - name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: POD_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
  - name: POD_UID
    valueFrom:
      fieldRef:
        fieldPath: metadata.uid
imagePullSecrets:
  - name: regcred
appName: azureinterview-broken-app
serviceAccount:
  create: true
  serviceAccountName: mechanicode

role:
  enabled: true
  name: mechanicode
  rules:
    - apiGroups: [""]
      resources: ["pods"]
      verbs: ["get", "list"]

roleBinding:
  enabled: true
  name: mechanicode-view-namespace
  namespace: mechanicode-go
  subjects:
    - kind: ServiceAccount
      name: mechanicode
  roleRef:
    kind: Role
    name: mechanicode

service:
  port: 8080
ingress:
  enabled: true
  name: azureinterview-broken-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  ingressClassName: nginx
  tls:
    hosts:
      - test.com # you'll need to change this
    secretName: azureinterview-broken-tls
  rules:
    - host: test.com # you'll need to change this
      http:
        paths:
          - path: /az/go/
            pathType: Prefix
            backend:
              service:
                name: azureinterview-broken-service
                port:
                  number: 80
          - path: /container-info
            pathType: Prefix
            backend:
              service:
                name: azureinterview-broken-service
                port:
                  number: 80
          - path: /static/img
            pathType: Prefix
            backend:
              service:
                name: azureinterview-broken-service
                port:
                  number: 80
autoscaling:
  enabled: false